__id__ = "sync_powersaver"
__name__ = "Powersaver Sync"
__description__ = "Synchronizes Telegram's power saving mode with system ones"
__icon__ = "nonPlugins/1"
__version__ = "2.0"
__min_version__ = "12.1.1"
__author__ = "@nonPlugins"
