[project]
name = "template"
version = "1.0"
description = "Plugin for exteraGram / Ayugram"
requires-python = "==3.11.*"

[dependency-groups]
dev = [
    "ruff>=0.15.0",
    "python-minifier>=3.2.0",
]

[tool.ruff]
target-version = "py311"
line-length = 160

[tool.ruff.lint]
select = ["E", "W", "F", "I", "B", "C4", "UP", "RUF", "TID"]
ignore = ["RUF001"]

[tool.ruff.lint.isort]
combine-as-imports = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
